version: '3.5'
services:
  minio:
    image: "minio/minio"
    container_name: minio
    entrypoint: ["sh", "-c", "mkdir -p /data/${BUCKET:-bucket} && minio server /data"]
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${ACCESS_KEY:-my-access-key}
      - MINIO_ROOT_PASSWORD=${SECRET_KEY:-my-secret-key}
    networks:
      - demo-network

networks:
  demo-network:
    name: demo-net

